language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      env: PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
      latex: false
      brew_packages: imagemagick --ignore-depends --build-from-source --verbose # should pick up on XQuartz x11/png/fc
      before_install: brew install webp librsvg xz # build depends only
    - os: osx
      osx_image: xcode7.2
      brew_packages: imagemagick webp librsvg
      latex: false
    - os: osx
      osx_image: xcode7.2
      latex: false
      brew_packages: imagemagick --with-fontconfig
      before_install:
        - brew install webp librsvg
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      latex: false
      before_install:
        - (while true; do echo 'Ping? Pong!'; sleep 500; done) &

addons:
  apt:
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev

r_github_packages:
  - jeroenooms/rsvg
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
