language: r
cache: packages
latex: false
r_build_args: '--no-build-vignettes'

matrix:
  include:
    - env: _R_CHECK_FORCE_SUGGESTS_=0
      r_check_args: '--ignore-vignettes'
      addons:
        apt:
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: imagemagick
    - os: osx
      latex: false
      osx_image: xcode8.3
      brew_packages: imagemagick --with-fontconfig --with-webp --with-librsvg --with-fftw
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - r-cran-rgdal

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi

# Prevents Travis timeout for building magick
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
