language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      latex: false
      osx_image: xcode8.1
      brew_packages: imagemagick
    - os: osx
      latex: false
      osx_image: xcode8.1
      brew_packages: imagemagick --with-fontconfig --with-webp --with-librsvg --with-fftw
    - os: osx
      latex: false
      osx_image: xcode8.1
      disable_homebrew: true
    - os: osx
      latex: false
      osx_image: beta-xcode6.4
      disable_homebrew: true

addons:
  apt:
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - r-cran-rgdal

r_packages:
  - rgdal

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

# Prevents Travis timeout for building magick
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
